name: CI
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Test
        run: bats -r .

      - name: Build docker image
        run: docker build .
